# Generated by Django 2.2.3 on 2019-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
