# Generated by Django 2.2.3 on 2019-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190726_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='blog/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
